// <auto-generated />
using System;
using COPILmatic_back.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(CopilmaticContext))]
    [Migration("20260416220126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__cm_categ__3213E83F8AD1C9F5");

                    b.ToTable("cm_category");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("EditionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edition_date");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("PK__cm_comme__3213E83FB46C06D5");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubjectId");

                    b.ToTable("cm_comment");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("AnnualAllocatedLoadDays")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("annual_allocated_load_days");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company_name");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__cm_custo__3213E83FD627A2CB");

                    b.ToTable("cm_customer");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("EditionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edition_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__cm_group__3213E83FBA5438E2");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("cm_group");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__cm_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_cm_refresh_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("cm_refresh_token", (string)null);
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("ActualLoadHours")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("actual_load_hours");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assigned_user_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edition_date");

                    b.Property<decimal?>("EstimatedLoadHours")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("estimated_load_hours");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__cm_subje__3213E83F35FFC490");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GroupId");

                    b.ToTable("cm_subject");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__cm_user__3213E83F52BF5AD0");

                    b.ToTable("cm_user");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.GroupHasUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.HasKey("UserId", "GroupId")
                        .HasName("PK__GROUP_HA__A4E94E55281D401F");

                    b.HasIndex("GroupId");

                    b.ToTable("GROUP_HAS_USER");
                });

            modelBuilder.Entity("CmCategoryCmGroup", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.HasKey("CategoryId", "GroupId");

                    b.ToTable("CmCategoryCmGroup");
                });

            modelBuilder.Entity("CmCustomerCmGroup", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.HasKey("CustomerId", "GroupId");

                    b.ToTable("CmCustomerCmGroup");
                });

            modelBuilder.Entity("GroupHasCategory", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("group_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.HasKey("GroupId", "CategoryId")
                        .HasName("PK__GROUP_HA__88237B3BFE958F51");

                    b.HasIndex("CategoryId");

                    b.ToTable("GROUP_HAS_CATEGORY", (string)null);
                });

            modelBuilder.Entity("GroupHasCustomer", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("group_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.HasKey("GroupId", "CustomerId")
                        .HasName("PK__GROUP_HA__99A1C9188F4A2A6F");

                    b.HasIndex("CustomerId");

                    b.ToTable("GROUP_HAS_CUSTOMER", (string)null);
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmComment", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "CreatedByUser")
                        .WithMany("CmComments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__cm_commen__creat__3C69FB99");

                    b.HasOne("COPILmatic_back.API.Entities.CmSubject", "Subject")
                        .WithMany("CmComments")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__cm_commen__subje__3D5E1FD2");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmGroup", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "CreatedByUser")
                        .WithMany("CmGroups")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__cm_group__create__2A4B4B5E");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmRefreshToken", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "User")
                        .WithMany("CmRefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__cm_refresh_token__user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmSubject", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "AssignedUser")
                        .WithMany("CmSubjectAssignedUsers")
                        .HasForeignKey("AssignedUserId")
                        .HasConstraintName("FK__cm_subjec__assig__37A5467C");

                    b.HasOne("COPILmatic_back.API.Entities.CmCategory", "Category")
                        .WithMany("CmSubjects")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__cm_subjec__categ__35BCFE0A");

                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "CreatedByUser")
                        .WithMany("CmSubjectCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__cm_subjec__creat__38996AB5");

                    b.HasOne("COPILmatic_back.API.Entities.CmCustomer", "Customer")
                        .WithMany("CmSubjects")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__cm_subjec__custo__36B12243");

                    b.HasOne("COPILmatic_back.API.Entities.CmGroup", "Group")
                        .WithMany("CmSubjects")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__cm_subjec__group__398D8EEE");

                    b.Navigation("AssignedUser");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.GroupHasUser", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmGroup", "Group")
                        .WithMany("GroupHasUsers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GROUP_HAS__group__48CFD27E");

                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "User")
                        .WithMany("GroupHasUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GROUP_HAS__user___47DBAE45");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupHasCategory", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__GROUP_HAS__categ__44FF419A");

                    b.HasOne("COPILmatic_back.API.Entities.CmGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GROUP_HAS__group__440B1D61");
                });

            modelBuilder.Entity("GroupHasCustomer", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmCustomer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__GROUP_HAS__custo__412EB0B6");

                    b.HasOne("COPILmatic_back.API.Entities.CmGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GROUP_HAS__group__403A8C7D");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmCategory", b =>
                {
                    b.Navigation("CmSubjects");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmCustomer", b =>
                {
                    b.Navigation("CmSubjects");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmGroup", b =>
                {
                    b.Navigation("CmSubjects");

                    b.Navigation("GroupHasUsers");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmSubject", b =>
                {
                    b.Navigation("CmComments");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmUser", b =>
                {
                    b.Navigation("CmComments");

                    b.Navigation("CmGroups");

                    b.Navigation("CmRefreshTokens");

                    b.Navigation("CmSubjectAssignedUsers");

                    b.Navigation("CmSubjectCreatedByUsers");

                    b.Navigation("GroupHasUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
