// <auto-generated />
using System;
using TaskManager.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("UUID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cm_category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f170089-7223-4f5a-9902-b0354fbe4e7a"),
                            Name = "Support"
                        },
                        new
                        {
                            Id = new Guid("236b71aa-9ef4-4e06-b951-6598062aa199"),
                            Name = "Debug"
                        },
                        new
                        {
                            Id = new Guid("57f93148-b137-4324-91cd-702dcdb7d562"),
                            Name = "Optimisation"
                        },
                        new
                        {
                            Id = new Guid("150ab93d-d6a1-47c2-bff4-9fa6f0998a06"),
                            Name = "Etude"
                        },
                        new
                        {
                            Id = new Guid("fdc5572c-bec1-4b7e-8efc-03fd3e1a2776"),
                            Name = "Evolution"
                        });
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("UUID()");

                    b.Property<decimal?>("ActualLoadHours")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("actual_load_hours");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assigned_user_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edition_date");

                    b.Property<decimal?>("EstimatedLoadHours")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("estimated_load_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("cm_subject");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("UUID()");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creation_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("cm_user");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmSubject", b =>
                {
                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "AssignedUser")
                        .WithMany("AssignedSubjects")
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("COPILmatic_back.API.Entities.CmCategory", "Category")
                        .WithMany("Subjects")
                        .HasForeignKey("CategoryId");

                    b.HasOne("COPILmatic_back.API.Entities.CmUser", "CreatedByUser")
                        .WithMany("CreatedSubjects")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmCategory", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("COPILmatic_back.API.Entities.CmUser", b =>
                {
                    b.Navigation("AssignedSubjects");

                    b.Navigation("CreatedSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
